### ISSUE TITLE
Agent aircraft type "add" throws error

### ISSUE THREAD

**Issue by kkaigle** [opensky-to/agent#68]
When opening aircraft types in agent, it often CTD's after client update to .5.1

When trying to add new variant from in sim detection, it causes error that the aircraft could not be added

**Comment by sushiat** [comment]
Will look at the client issue first, but the agent code is unchanged so wondering what would cause that. What sim are you using?

**Comment by kkaigle** [comment]
> Will look at the client issue first, but the agent code is unchanged so wondering what would cause that. What sim are you using?

Xplane 12.
