### ISSUE TITLE
Disabling time autoset flags 

### ISSUE THREAD

**Issue by kkaigle** [opensky-to/agent#75]
![image](https://github.com/opensky-to/agent/assets/83706649/9ceb73de-963e-4d1b-abc1-985981264f63)
In xplane, if you uncheck autoset time, it seems to flag it even though the time is the same. I would suggest not forcing time for player enjoyment and scenery enjoyment

Additionally, something to keep in mind (MSFS does this now too), sims will slow the world time in order to calculate certain physics. Originally MSFS didnt do this, but recently its been seen. XP is much worse in this probably though. 

What happens is when you dip below the benchmark FPS (20 in XP), it slows the time in sim, in order to continue to calculate flight model per frame properly. When frames are generated too slowly, the sim doesnt keep real time anymore. I am guessing MSFS keeps real time counted, so it may not be an issue there. I would say though, removing the time requirement wont impact gameplay in my own opinion.

**Comment by sushiat** [comment]
Yeah that one is one of the things that kinda came from the onair origins. Agree that in the VA world I moved into nobody cares. Exception would be flying on vatsim where you are supposed to stay on real time. Could be one those small xp bonuses if you keep it on, but rework it so it shows/explains that and doesn't force it.

**Comment by sushiat** [comment]
Wil be implemented in #79
