### ISSUE TITLE
warping detected

### ISSUE THREAD

**Issue by kkaigle** [opensky-to/agent#82]
Low priority, at some point need to look into what is causing detected warpage when none was used. Will continue to triage
![image](https://github.com/opensky-to/agent/assets/83706649/10e90f53-730d-43c4-930d-60652bdf11e1)

**Comment by sushiat** [comment]
Did skip any ground handling?

**Comment by kkaigle** [comment]
Ahh ok, just tested that. In fact that was the case, didnt know that would add on to the warp. Cool actually, makes you pay for the time in some way. Issue closed.

**Comment by sushiat** [comment]
Not ignorance, lack of documentation - maybe fitting you started that gitbook page last night. FAQ is calling for something like that.
